server:
  port: 8081

spring:
  application:
    name: service-1
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        register: true
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
