spring:
  application:
    name: service-2
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
server:
  port: 8082
